version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: server
    volumes:
      - graphql_express_node_modules_volume:/usr/src/node_modules
      - .:/usr/src/app
    command: yarn dev
    expose:
      - 3000
    ports:
      - '3000:3000'

volumes:
  graphql_express_node_modules_volume:
